title: OSDG Winter of Code
license: GNU AFFERO GENERAL PUBLIC LICENSE V3.0
organization: OSDG
description: A website that showcases interesting projects, using Angular JS.
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site
logo: "resources/images/osdg.png"
logo-link: http://osdg.iiit.ac.in/

plugins:
  - jekyll-netlify

# Build settings
destination: ./docs
exclude: [vendor]
markdown: kramdown
collections:
  projects:
    output: true
  faq:
    output: true
